# Generated by Django 5.0.7 on 2024-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concrete", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="prompt",
        ),
        migrations.AddField(
            model_name="message",
            name="message_status",
            field=models.CharField(
                choices=[
                    ("UNPROCESSED", "Unprocessed"),
                    ("PROCESSING", "Processing"),
                    ("PROCESSED", "Processed"),
                ],
                default="UNPROCESSED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="orchestrator",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="result",
            field=models.TextField(default=""),
        ),
    ]
