# Generated by Django 5.0.7 on 2024-08-02 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "concrete",
            "0002_rename_content_message_prompt_message_message_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
