services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    volumes:
      - shared-volume:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "8080:80"
    depends_on:
      - dind-builder

  dind-builder:
    build:
      context: .
      dockerfile: Dockerfile.dind-builder
    volumes:
      - shared-volume:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SHARED_VOLUME=/shared
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    privileged: true
    ports:
      - "5000:5000"

volumes:
  shared-volume: