[project]
name = "main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9, <4.0.0"
dependencies = [
    "concrete-core[auth,requests,openai,google-auth]>=0.0.4",
    "concrete-db>=0.0.0",
    "webapp-common",
]
