FROM python:3.11.10-bookworm

RUN pip install uv==0.4.27

WORKDIR /app
COPY src ./src 
COPY pyproject.toml .
COPY uv.lock .
# RUN uv sync

COPY webapp/api ./webapp/api
WORKDIR /app/webapp/api
 
# App specifics
RUN chmod +x /app/webapp/api/scripts/start.sh

EXPOSE 80
CMD ["/app/webapp/api/scripts/start.sh"]
