FROM python:3.11.10-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.4.27 /uv /uvx /bin/


WORKDIR /app

COPY pyproject.toml uv.lock .env ./
COPY src ./src

COPY webapp/daemons ./webapp/daemons
COPY webapp/common.py webapp/__init__.py ./webapp/

RUN uv sync

RUN chmod +x /app/webapp/daemons/scripts/start.sh
EXPOSE 80
CMD ["/app/webapp/daemons/scripts/start.sh"]