services:
  demo:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.demo
    image: webapp-demo:latest
    container_name: webapp-demo
    volumes:
      - shared-volume:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "8000:80"
    depends_on:
      - dind-builder
    env_file: "../.env.demo"

  dind-builder:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dind-builder
    image: dind-builder:latest
    container_name: dind-builder
    privileged: true
    volumes:
      - /shared:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - 5000:5000
    env_file:
      - ../.env.dind-builder

volumes:
  shared-volume:
