services:
  webapp-demo:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.demo
    image: webapp-demo:latest
    container_name: webapp-demo
    volumes:
      - shared-volume:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "8000:80"
    env_file: 
      - path: ".env.demo"
        required: false
    networks:
      - concrete_network
    platform: linux/arm64

  dind-builder:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dind-builder
    image: dind-builder:latest
    container_name: dind-builder
    privileged: true
    volumes:
      - /shared:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "5002:5002"
    env_file:
      - path: ".env.dind-builder"
        required: false
    networks:
      - concrete_network
    platform: linux/arm64

  webapp-main:
    ports:
      - 8001:80
    image: webapp-main
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.main
    container_name: webapp-main
    networks:
      - concrete_network
    platform: linux/arm64

volumes:
  shared-volume:

networks:
  concrete_network:
    driver: bridge
