services:
  demo:
    image: webapp-demo:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.demo
    volumes:
      - shared-volume:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "8000:80"
    depends_on:
      - dind-builder
    env_file: "../.env"

  dind-builder:
    image: webapp-dind-builder:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dind-builder
      platforms:
        - linux/arm64
    volumes:
      - shared-volume:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SHARED_VOLUME=/shared
    privileged: true
    ports:
      - "5002:5002"
    env_file: "../.env"

volumes:
  shared-volume:
