FROM python:3.11.9-slim-bookworm

# TODO: Reconsider the use of build-time arg injection (vs. runtime)
ARG GH_WEBHOOK_SECRET
ARG GH_CLIENT_ID
ARG GH_PRIVATE_KEY_PATH
# ARG OPENAI_API_KEY
# ARG OPENAI_TEMPERATURE

ENV GH_WEBHOOK_SECRET=$GH_WEBHOOK_SECRET
ENV GH_CLIENT_ID=$GH_CLIENT_ID
ENV GH_PRIVATE_KEY_PATH=$GH_PRIVATE_KEY_PATH
# ENV OPENAI_API_KEY=$OPENAI_API_KEY
# ENV OPENAI_TEMPERATURE=$OPENAI_TEMPERATURE

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VERSION=1.8  
ENV POETRY_HOME=/opt/poetry
ENV PATH=$POETRY_HOME/bin:$PATH

WORKDIR /app

RUN apt-get update
RUN pip install "poetry==$POETRY_VERSION"

COPY pyproject.toml poetry.lock README.md ./ 
COPY concrete ./concrete
COPY webapp/daemons ./webapp/daemons

RUN poetry config virtualenvs.create false && \
    poetry install --only daemons,main,tooluse,webapp

RUN chmod +x ./webapp/daemons/scripts/start.sh

EXPOSE 80
CMD ["./webapp/daemons/scripts/start.sh"]