FROM python:3.11.10-bookworm AS builder

RUN pip install uv==0.4.27 

WORKDIR /app

# Common deps
COPY pyproject.toml uv.lock .env ./
COPY src ./src

# App specifics
COPY webapp/main ./webapp/main
COPY webapp/webapp-common ./webapp/webapp-common

WORKDIR /app/webapp/main
RUN uv sync
RUN chmod +x /app/webapp/main/scripts/start.sh

EXPOSE 80
CMD ["/app/webapp/main/scripts/start.sh"]

