FROM python:3.11.10-bookworm 

RUN pip install uv==0.4.27

WORKDIR /app
# Common deps
COPY pyproject.toml uv.lock .env ./
COPY src ./src
# App specifics
COPY webapp/auth ./webapp/auth
COPY webapp/common.py webapp/__init__.py webapp/pyproject.toml ./webapp/

RUN chmod +x ./webapp/auth/scripts/start.sh
EXPOSE 80
CMD ["./webapp/auth/scripts/start.sh"]

