FROM python:3.11.10-bookworm 

RUN pip install uv==0.4.27

WORKDIR /app
# Common deps
COPY pyproject.toml uv.lock .env ./
COPY src ./src

# App specifics

COPY webapp/homepage ./webapp/homepage
COPY webapp/__init__.py webapp/common.py ./webapp/
WORKDIR /app/webapp/homepage
RUN uv sync
RUN chmod +x /app/webapp/homepage/scripts/start.sh

EXPOSE 80
CMD ["/app/webapp/homepage/scripts/start.sh"]

