FROM python:3.11.10-bookworm AS builder

RUN pip install uv==0.4.27

WORKDIR /app

COPY pyproject.toml uv.lock .env ./
COPY src ./src

COPY alembic.ini alembic.ini
COPY migrations migrations
COPY scripts/run_alembic_migrations.sh scripts/run_alembic_migrations.sh

RUN uv sync
RUN chmod +x scripts/run_alembic_migrations.sh
CMD ["./scripts/run_alembic_migrations.sh"]

