FROM python:3.11.9-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VERSION=1.8
ENV POETRY_HOME=/opt/poetry
ENV PATH=$POETRY_HOME/bin:$PATH
ENV OPENAI_TEMPERATURE=0

WORKDIR /app

RUN apt-get update

RUN pip install "poetry==$POETRY_VERSION"

COPY pyproject.toml poetry.lock README.md /app/
COPY concrete /app/concrete
RUN poetry config virtualenvs.create false 
RUN poetry install --only webapp-homepage,main

COPY /webapp/homepage ./

RUN chmod +x ./scripts/start.sh

EXPOSE 80
CMD ["./scripts/start.sh"]