FROM python:3.11.10-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.4.27 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock .env ./
COPY src ./src

COPY alembic.ini alembic.ini
COPY migrations migrations
COPY scripts/run_alembic_migrations.sh scripts/run_alembic_migrations.sh

RUN uv sync
RUN chmod +x scripts/run_alembic_migrations.sh
CMD ["./scripts/run_alembic_migrations.sh"]

