FROM python:3.11.9-slim-bookworm

ARG GH_WEBHOOK_SECRET
ARG GH_CLIENT_ID

ENV GH_WEBHOOK_SECRET=$GH_WEBHOOK_SECRET
ENV GH_CLIENT_ID=$GH_CLIENT_ID
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VERSION=1.8  
ENV POETRY_HOME=/opt/poetry
ENV PATH=$POETRY_HOME/bin:$PATH
ENV OPENAI_TEMPERATURE=0

WORKDIR /app

RUN apt-get update
RUN pip install "poetry==$POETRY_VERSION"

COPY pyproject.toml poetry.lock README.md ./ 
COPY concrete ./concrete
COPY webapp/daemons ./webapp/daemons

RUN poetry config virtualenvs.create false && \
    poetry install --only daemons,main

RUN chmod +x ./webapp/daemons/scripts/start.sh

EXPOSE 80
CMD ["./webapp/daemons/scripts/start.sh"]