FROM python:3.11.10-bookworm 

RUN pip install uv==0.4.27

WORKDIR /app
# Common deps
COPY pyproject.toml uv.lock .env ./
COPY src ./src
# App specifics
COPY webapp/__init__.py webapp/common.py ./webapp/
COPY webapp/auth ./webapp/auth
RUN uv sync
RUN chmod +x ./webapp/auth/scripts/start.sh
EXPOSE 80
CMD ["./webapp/auth/scripts/start.sh"]

