FROM python:3.11.10-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.4.27 /uv /uvx /bin/


WORKDIR /app

COPY .env .env
COPY pyproject.toml uv.lock .env ./
COPY src ./src

COPY webapp/agentserver ./webapp/agentserver
COPY webapp/webapp-common ./webapp/webapp-common

WORKDIR /app/webapp/agentserver
RUN uv sync

RUN chmod +x /app/webapp/agentserver/scripts/start.sh
EXPOSE 80
CMD ["/app/webapp/agentserver/scripts/start.sh"]