services:
  tailscale-authkey1:
      image: tailscale/tailscale:latest
      container_name: ts-authkey-test
      hostname: tailscale-authkey-kZU
      environment:
        - TS_AUTHKEY=tskey-auth-kZUHeFJxpM11CNTRL-w583zA12GyPuHxQar3JrxPqWw54FwreVT
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_USERSPACE=false
      volumes:
        - ts-authkey-test:/var/lib/tailscale
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - net_admin
        - sys_module
      restart: unless-stopped

  webapp-demo:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.demo
    image: webapp-demo:latest
    container_name: webapp-demo
    volumes:
      - shared-volume:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "8000:80"
    env_file: 
      - path: "../.env.demo"
        required: false
    networks:
      - concrete_network
    platform: linux/arm64

  dind-builder:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dind-builder
    image: dind-builder:latest
    container_name: dind-builder
    privileged: true
    volumes:
      - /shared:/shared
    environment:
      - SHARED_VOLUME=/shared
    ports:
      - "5002:5002"
    env_file:
      - path: "../.env.dind-builder"
        required: false
    networks:
      - concrete_network
    platform: linux/arm64

  webapp-homepage:
    ports:
      - 8001:80
    image: webapp-homepage
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.homepage
    container_name: webapp-homepage
    env_file:
      - path: "../.env"
        required: false
    networks:
      - concrete_network
    platform: linux/arm64

volumes:
  shared-volume:

networks:
  concrete_network:
    driver: bridge
