FROM python:3.11.9-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VERSION=1.5.1
ENV POETRY_HOME=/opt/poetry
ENV PATH=$POETRY_HOME/bin:$PATH
ENV OPENAI_TEMPERATURE=0

WORKDIR /app

RUN apt-get update

RUN pip install "poetry==$POETRY_VERSION"

COPY . .

RUN poetry config virtualenvs.create false \
    && poetry install --without dev --no-interaction --no-ansi

RUN chmod +x ./demo_webapp/scripts/start.sh
EXPOSE 80

CMD ["./demo_webapp/scripts/start.sh"]