# FROM caddy:2.8.4-alpine

# WORKDIR /app

# COPY site ./site

# EXPOSE 80
# CMD ["caddy", "file-server", "--root", "/app/site"]


FROM python:3.11.10-bookworm

RUN pip install uv==0.4.27

WORKDIR /app

COPY pyproject.toml uv.lock .env ./
COPY src ./src

COPY webapp/docs ./webapp/docs
WORKDIR /app/webapp/docs
RUN uv sync
RUN chmod +x /app/webapp/docs/scripts/start.sh
EXPOSE 80
CMD ["caddy", 'file-server', '--root', '/app/
