FROM python:3.11.10-bookworm

RUN pip install uv==0.4.27

WORKDIR /app
COPY src ./src 
COPY pyproject.toml .

COPY .env .

# App specifics
COPY webapp/pyproject.toml ./webapp/pyproject.toml
COPY webapp/api ./webapp/api
WORKDIR /app/webapp/api
RUN uv sync
RUN chmod +x /app/webapp/api/scripts/start.sh
EXPOSE 80
CMD ["/app/webapp/api/scripts/start.sh"]
