"""add tools

Revision ID: 0332575ee705
Revises: cb991c369855
Create Date: 2024-10-16 14:57:18.295978

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0332575ee705'
down_revision: Union[str, None] = 'cb991c369855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.create_unique_constraint(None, 'tool', ['name'])
    op.add_column('operatortoollink', sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'operatortoollink', 'tool', ['tool_name'], ['name'])
    op.drop_constraint('operatortoollink_tool_id_fkey', 'operatortoollink', type_='foreignkey')
    op.drop_column('operatortoollink', 'tool_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='unique')
    op.drop_column('tool', 'name')
    op.add_column('operatortoollink', sa.Column('tool_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'operatortoollink', type_='foreignkey')
    op.create_foreign_key('operatortoollink_tool_id_fkey', 'operatortoollink', 'tool', ['tool_id'], ['id'])
    op.drop_column('operatortoollink', 'tool_name')
    # ### end Alembic commands ###
