"""Add user relationship to operators

Revision ID: 17d8611620a7
Revises: 3bb0633b746d
Create Date: 2025-01-03 15:26:09.466908

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '17d8611620a7'
down_revision: Union[str, None] = '3bb0633b746d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operator', 'orchestrator_id', existing_type=sa.UUID(), nullable=True)
    op.create_index('unique_name_when_orchestrator_null', 'operator', ['name'], unique=True, postgresql_where=False)
    op.drop_constraint('operatortoollink_operator_id_fkey', 'operatortoollink', type_='foreignkey')
    op.drop_constraint('operatortoollink_tool_id_fkey', 'operatortoollink', type_='foreignkey')
    op.create_foreign_key(None, 'operatortoollink', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operatortoollink', type_='foreignkey')
    op.create_foreign_key('operatortoollink_tool_id_fkey', 'operatortoollink', 'tool', ['tool_id'], ['id'])
    op.create_foreign_key('operatortoollink_operator_id_fkey', 'operatortoollink', 'operator', ['operator_id'], ['id'])
    op.drop_index('unique_name_when_orchestrator_null', table_name='operator', postgresql_where=False)
    op.alter_column('operator', 'orchestrator_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
