"""Add Log Table

Revision ID: 1c319faf3339
Revises: 3bb0633b746d
Create Date: 2025-01-10 11:19:36.968341

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c319faf3339'
down_revision: Union[str, None] = '3bb0633b746d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'log',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    # Unsure where these constraints are coming from? They seem fine though.
    # Adds a cascading delete to tools.
    op.drop_constraint('operatortoollink_operator_id_fkey', 'operatortoollink', type_='foreignkey')
    op.drop_constraint('operatortoollink_tool_id_fkey', 'operatortoollink', type_='foreignkey')
    op.create_foreign_key(None, 'operatortoollink', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operatortoollink', type_='foreignkey')
    op.create_foreign_key('operatortoollink_tool_id_fkey', 'operatortoollink', 'tool', ['tool_id'], ['id'])
    op.create_foreign_key('operatortoollink_operator_id_fkey', 'operatortoollink', 'operator', ['operator_id'], ['id'])
    op.drop_table('log')
    # ### end Alembic commands ###
