"""Add tools

Revision ID: 22b22e75b323
Revises: fc7723965373
Create Date: 2024-10-17 12:09:36.750912

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22b22e75b323'
down_revision: Union[str, None] = 'fc7723965373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column('tool', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tool', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_column('tool', 'user_id')
    op.drop_column('tool', 'name')
    # ### end Alembic commands ###
