"""title columns renamed to name

Revision ID: 3ccb07623f0b
Revises: cb991c369855
Create Date: 2024-10-09 17:50:04.384378

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ccb07623f0b'
down_revision: Union[str, None] = 'cb991c369855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'type_name', new_column_name='type')
    op.alter_column('operator', 'title', new_column_name='name')
    op.create_unique_constraint('no_duplicate_operators_per_orchestrator', 'operator', ['name', 'orchestrator_id'])
    op.alter_column(
        'orchestrator', 'type_name', new_column_name='type', existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.alter_column('orchestrator', 'title', new_column_name='name')
    op.create_unique_constraint('no_duplicate_names_per_user', 'orchestrator', ['name', 'user_id'])
    op.alter_column('project', 'title', new_column_name='name')
    op.create_unique_constraint('no_duplicate_projects_per_orchestrator', 'project', ['name', 'orchestrator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('no_duplicate_projects_per_orchestrator', 'project', type_='unique')
    op.alter_column('project', 'name', new_column_name='title')
    op.drop_constraint('no_duplicate_names_per_user', 'orchestrator', type_='unique')
    op.alter_column('orchestrator', 'name', new_column_name='title')
    op.alter_column(
        'orchestrator', 'type', new_column_name='type_name', existing_type=sa.VARCHAR(length=32), nullable=False
    )

    op.drop_constraint('no_duplicate_operators_per_orchestrator', 'operator', type_='unique')
    op.alter_column('operator', 'name', new_column_name='title')
    op.alter_column('message', 'type', new_column_name='type_name')
    # ### end Alembic commands ###
