"""add foo

Revision ID: 86877f507aca
Revises: ad1893077e4f
Create Date: 2024-10-04 10:58:56.397787

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86877f507aca'
down_revision: Union[str, None] = 'ad1893077e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator', sa.Column('foo', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operator', 'foo')
    # ### end Alembic commands ###
