"""foo

Revision ID: bc9c728d1933
Revises: 0332575ee705
Create Date: 2024-10-17 10:12:29.931241

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc9c728d1933'
down_revision: Union[str, None] = '0332575ee705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operatortoollink', sa.Column('tool_id', sa.Uuid(), nullable=False))
    op.drop_constraint('operatortoollink_tool_name_fkey', 'operatortoollink', type_='foreignkey')
    op.create_foreign_key(None, 'operatortoollink', 'tool', ['tool_id'], ['id'])
    op.drop_column('operatortoollink', 'tool_name')
    op.add_column('tool', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('tool_name_key', 'tool', type_='unique')
    op.create_foreign_key(None, 'tool', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.create_unique_constraint('tool_name_key', 'tool', ['name'])
    op.drop_column('tool', 'user_id')
    op.add_column('operatortoollink', sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'operatortoollink', type_='foreignkey')
    op.create_foreign_key('operatortoollink_tool_name_fkey', 'operatortoollink', 'tool', ['tool_name'], ['name'])
    op.drop_column('operatortoollink', 'tool_id')
    # ### end Alembic commands ###
