"""project, message models and relationships

Revision ID: cb991c369855
Revises: b95be09d8b45
Create Date: 2024-10-08 09:29:08.704493

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb991c369855"
down_revision: Union[str, None] = "b95be09d8b45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("orchestrator_id", sa.Uuid(), nullable=False),
        sa.Column("executive_id", sa.Uuid(), nullable=True),
        sa.Column("developer_id", sa.Uuid(), nullable=True),
        sa.Column("direct_message_operator_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["developer_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(["direct_message_operator_id"], ["operator.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["executive_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(["orchestrator_id"], ["orchestrator.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("direct_message_operator_id"),
    )
    op.add_column("message", sa.Column("project_id", sa.Uuid(), nullable=False))
    op.add_column("message", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.add_column("message", sa.Column("operator_id", sa.Uuid(), nullable=True))
    op.drop_constraint("message_orchestrator_id_fkey", "message", type_="foreignkey")
    op.create_foreign_key(None, "message", "project", ["project_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "message", "operator", ["operator_id"], ["id"])
    op.create_foreign_key(None, "message", "user", ["user_id"], ["id"])
    op.drop_column("message", "orchestrator_id")
    op.add_column(
        "operator",
        sa.Column("profile_picture_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("profile_picture_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.create_unique_constraint(None, "user", ["email"])
    op.drop_column("user", "profile_picture")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "profile_picture",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_column("user", "profile_picture_url")
    op.drop_column("operator", "profile_picture_url")
    op.add_column(
        "message",
        sa.Column("orchestrator_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_orchestrator_id_fkey",
        "message",
        "orchestrator",
        ["orchestrator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("message", "operator_id")
    op.drop_column("message", "user_id")
    op.drop_column("message", "project_id")
    op.drop_table("project")
    # ### end Alembic commands ###
