FROM python:3.11.9-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update
RUN pip install flask
RUN pip install concrete-operators

COPY . .

RUN chmod +x start.sh
EXPOSE 80
CMD ["./start.sh"]