# I don't  think we can remove the [project] section.
[project]
name = "uv"
version = "0.1.0"
requires-python = ">=3.11.9"
dependencies = [
    "concrete-db",
    "concrete-core[openai,auth,google-auth,requests]",
    'gunicorn>=23.0.0',
    "uvicorn>=0.32.0",
    'fastapi',
]

[tool.uv.sources]
concrete-core = { path = "../../src/concrete-core" }
concrete-db = { path = "../../src/concrete-db" }

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true


