[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9, <4.0.0"
dependencies = [
    "mkdocs>=1.6.1",
    "pymdown-extensions>=10.12",
]


