name: Deploy API to Prod
on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Setup Python for poetry
              uses: actions/setup-python@v5
              with:
                python-version: "3.11.9"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS Credentials for ECS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
                  aws-region: us-east-1

            - name: Deploy to ECS staging using AwsTool._deploy_service
              env:
                  OPENAI_API_KEY: ${{ secrets.DEMO_OPENAI_API_KEY }}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
                  DB_HOST: ${{secrets.DB_HOST}}
                  HTTP_ALLOWED_HOSTS: ${{secrets.HTTP_ALLOWED_HOSTS}}
                  HTTP_CORS_ORIGINS: ${{secrets.HTTP_CORS_ORIGINS}}
                  HTTP_SESSION_DOMAIN: ${{secrets.HTTP_SESSION_DOMAIN}}
                  HTTP_SESSION_SECRET: ${{secrets.HTTP_SESSION_SECRET}}
                  SAAS_AUTH_REDIRECT: ${{secrets.SAAS_AUTH_REDIRECT}}
                  GOOGLE_OAUTH_CLIENT_ID: ${{secrets.GOOGLE_OAUTH_CLIENT_ID}}
                  GOOGLE_OAUTH_CLIENT_SECRET: ${{secrets.GOOGLE_OAUTH_CLIENT_SECRET}}
                  GOOGLE_OAUTH_REDIRECT_URIS: ${{secrets.GOOGLE_OAUTH_REDIRECT_URIS}}
                  GOOGLE_OAUTH_REDIRECT: ${{secrets.GOOGLE_OAUTH_REDIRECT}}
              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  poetry --version
                  poetry install
                  touch .env
                  echo OPENAI_TEMPERATURE=0 > .env
                  echo OPENAI_API_KEY=$OPENAI_API_KEY >> .env 
                  echo DB_DRIVER=postgresql+psycopg >> .env
                  echo DB_USERNAME=postgres >> .env
                  echo DB_PASSWORD=$DB_PASSWORD >> .env
                  echo DB_PORT=5432 >> .env
                  echo DB_HOST=$DB_HOST >> .env
                  echo DB_DATABASE=postgres >> .env

                  echo HTTP_ALLOWED_HOSTS=$HTTP_ALLOWED_HOSTS >> .env
                  echo HTTP_CORS_ORIGINS=$HTTP_CORS_ORIGINS >> .env
                  echo HTTP_SESSION_DOMAIN=$HTTP_SESSION_DOMAIN >> .env
                  echo HTTP_SESSION_SECRET=$HTTP_SESSION_SECRET >> .env
                  echo SAAS_AUTH_REDIRECT=$SAAS_AUTH_REDIRECT >> .env

                  echo GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID >> .env
                  echo GOOGLE_OAUTH_CLIENT_SECRET=$GOOGLE_OAUTH_CLIENT_SECRET >> .env
                  echo GOOGLE_OAUTH_REDIRECT_URIS=$GOOGLE_OAUTH_REDIRECT_URIS >> .env
                  echo GOOGLE_OAUTH_REDIRECT=$GOOGLE_OAUTH_REDIRECT >> .env
                  poetry run python -m concrete deploy \
                    --image-uri 008971649127.dkr.ecr.us-east-1.amazonaws.com/api:latest \
                    --container-name api \
                    --container-port 80 \
                    --container-env-file .env \
                    --listener-rule-field host-header \
                    --listener-rule-value api.abop.ai \

# https://github.com/actions/deploy-pages/issues/329 -
# https://github.com/github/docs/issues/32320 - Explains why id-token write is needed
# The id-token: write permission provides a workflow the ability to interact with external services that use OpenID Connect (OIDC).
permissions:
  id-token: write 
  contents: read