name: Code Formatting
run-name: Code Format ${{  github.actor }}
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: mypy
        run: |
          pip install mypy
          mypy -p concrete
      - name: flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          ignore: "W293"
      - name: black
        uses: psf/black@stable
        with:
          options: "--check --verbose --skip-string-normalization --line-length=120"
      - name: isort
        uses: isort/isort-action@v1 
        with:
          configuration: "--check-only --diff --profile black"

  bandit:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: bandit 
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          level: high
          confidence: high
          exit_zero: true  # force success. could be noisy, so try this for now
          skips: B101,B601
