name: Deploy Daemons to Staging
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Configure AWS credentials for ECR
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecr-write-access
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  mask-password: "true"

            - name: Build the images
              env:
                GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
                GH_PRIVATE_KEY_PATH: ${{ secrets.GH_PRIVATE_KEY_PATH }}
              run: |
                  echo "$GH_PRIVATE_KEY" >> "./webapp/daemons/$GH_PRIVATE_KEY_PATH"
                  touch .env
                  make build-daemons

            - name: Push to ECR
              run: |
                  make aws-ecr-push-daemons
    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Setup Python for poetry
              uses: actions/setup-python@v5
              with:
                python-version: "3.11.9"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS Credentials for ECS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
                  aws-region: us-east-1

            - name: Deploy to ECS staging using AwsTool._deploy_service
              env:
                GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
                GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
                GH_PRIVATE_KEY_PATH: ${{ secrets.GH_PRIVATE_KEY_PATH }}
                GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
                OPENAI_API_KEY: ${{ secrets.DEMO_OPENAI_API_KEY }}
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  poetry --version
                  poetry install
                  echo GH_WEBHOOK_SECRET=$GH_WEBHOOK_SECRET >> .env
                  echo GH_CLIENT_ID=$GH_CLIENT_ID >> .env
                  echo GH_PRIVATE_KEY_PATH=$GH_PRIVATE_KEY_PATH >> .env
                  echo OPENAI_API_KEY=$OPENAI_API_KEY >> .env
                  echo OPENAI_TEMPERATURE=0 >> .env
                  
                  poetry run python -m concrete deploy \
                    --image-uri 008971649127.dkr.ecr.us-east-1.amazonaws.com/daemons:latest \
                    --container-name daemons-staging \
                    --container-port 80 \
                    --container-env-file .env \
                    --service-name=daemons-staging

# https://github.com/actions/deploy-pages/issues/329 -
# https://github.com/github/docs/issues/32320 - Explains why id-token write is needed
# The id-token: write permission provides a workflow the ability to interact with external services that use OpenID Connect (OIDC).
permissions:
  id-token: write 
  contents: read