name: Deploy to Staging

on:
  push:
    branches:
      - michael/gha_staging

jobs:
  build-and-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::008971649127:role/gha-ecr-write-access
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Create .env.demo file
        run: |
          echo "OPENAI_API_KEY=${{secrets.DEMO_OPENAI_API_KEY}}" >> .env.demo
          echo "OPENAI_TEMPERATURE=0" >> .env.demo

      - name: Build and push to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: webapp-demo-staging
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose -f docker/docker-compose.yml build webapp-demo
          docker tag webapp-demo:latest ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          docker push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      - name: Configure AWS Credentials for ECS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
          aws-region: us-east-1

      - name: Deploy to ECS staging using DeployToAWS._deploy_image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: webapp-demo-staging
          IMAGE_TAG: ${{ github.sha }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry install
          echo "from concrete.tools import DeployToAWS; DeployToAWS._deploy_image(image_uri='${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}')" | poetry run python3 

          
permissions:
  id-token: write
  contents: read
