name: Deploy Webapps to Staging
on:
#   workflow_dispatch:
#     inputs:
#       run_job:
#         description: 'Specify which job(s) to run'
#         required: false
#         default: 'all'
    push:
        branches:
            - michael/workflows



jobs:
    setup-venv:
        name: Setup venv for future builds/deployments
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with: 
                python-version-file: 'pyproject.toml'

            - name: Setup environment
              run: uv sync --all-extras --dev
            
            - name: Cache venv
              uses: actions/cache@v4
              with:
                path: .venv
                key: venv-${{runner.os}}-${{hashFiles('uv.lock')}}
                restore-keys: venv-${{runner.os}}-
