name: Deploy to Staging

on:
  push:
    branches:
      - michael/gha_staging

jobs:
  login-to-amazon-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::008971649127:role/GHA_ECR
          aws-region: us-east-1
          output-credentials: true
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "false"

    # outputs:
    #   registry: ${{ steps.login-ecr.outputs.registry }}
    #   docker_username: ${{ steps.login-to-amazon-ecr.outputs.docker_username_123456789012_dkr_ecr_us_east_1_amazonaws_com }} # More information on these outputs can be found below in the 'Docker Credentials' section
    #   docker_password: ${{ steps.login-to-amazon-ecr.outputs.docker_password_123456789012_dkr_ecr_us_east_1_amazonaws_com }}

permissions:
  id-token: write
  contents: read
# run-with-internal-service:
#     name: Run something with an internal image as a service
#     needs: login-to-amazon-ecr
#     runs-on: ubuntu-latest
#     services:
#     internal-service:
#         image: ${{ needs.login-to-amazon-ecr.outputs.registry }}/my-ecr-repo:latest
#         credentials:
#         username: ${{ needs.login-to-amazon-ecr.outputs.docker_username }}
#         password: ${{ needs.login-to-amazon-ecr.outputs.docker_password }}
#         ports:
#         - '80:80'
