name: Deploy Webapps to Staging
run-name: Deploy Webapps to Staging
on:
#   workflow_dispatch:
#     inputs:
#       run_job:
#         description: 'Specify which job(s) to run'
#         required: false
#         default: 'all'
    push:
        branches:
            - michael/workflows


jobs:
    setup-venv:
        name: Cache venv
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with: 
                python-version-file: 'pyproject.toml'
        
            - uses: astral-sh/setup-uv@v3
              with:
                version: "0.4.27"

            - run: uv sync --all-extras --dev
            
            - name: Cache venv
              uses: actions/cache@v4
              with:
                path: .venv
                key: venv-${{runner.os}}-${{hashFiles('uv.lock')}}
                restore-keys: venv-${{runner.os}}-
    
    build-and-deploy: 
        name: Builds and Deploy to Staging
        runs-on: ubuntu-latest
        needs: setup-venv
        environment: staging
        strategy:
            fail-fast: false
            matrix:
                image: ['api', 'main', 'homepage', 'auth']

        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3
            
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecr-write-access
                  aws-region: us-east-1

            - id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  mask-password: "true" 

            - uses: actions/setup-python@v5
              with:
                python-version-file: 'pyproject.toml'

            - name: Restore venv
              uses: actions/cache@v4
              with:
                path: .venv
                key: venv-${{runner.os}}-${{hashFiles('uv.lock')}}
                restore-keys: venv-${{runner.os}}-
           
            - name: Build the images
              run: |
                touch .env 
                make build-app APP=${{ matrix.image }}
                
            - name: Push to ECR
              run: make aws-ecr-push APP=${{ matrix.image }}
            
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
                  aws-region: us-east-1
            
            - name: Set up .env file for api
              if: matrix.image == 'api' 
              run: |
                touch .env
                echo OPENAI_API_KEY=${{ secrets.DEMO_OPENAI_API_KEY }} > .env
                echo OPENAI_TEMPERATURE=0 >> .env
                echo DB_DRIVER=postgresql+psycopg >> .env 
                echo DB_USERNAME=postgres >> .env
                echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
                echo DB_PORT=5432 >> .env
                echo DB_HOST=${{ secrets.DB_HOST }} >> .env
                echo DB_DATABASE=postgres >> .env

                echo GOOGLE_OAUTH_CLIENT_ID=1079616795937-oo3obhti3cv2npc4j6i06l5pq61v7925.apps.googleusercontent.com >> .env
                echo HTTP_SESSION_DOMAIN=abop.ai >> .env
                echo HTTP_SESSION_SECRET=${{ secrets.HTTP_SESSION_SECRET }} >> .env

            - name: Set up .env file for main
              if: matrix.image == 'main'
              run: |
                touch .env
                echo OPENAI_TEMPERATURE=0 > .env
                echo OPENAI_API_KEY=${{ secrets.DEMO_OPENAI_API_KEY }} >> .env
                echo DB_DRIVER=postgresql+psycopg >> .env
                echo DB_USERNAME=postgres >> .env
                echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
                echo DB_PORT=5432 >> .env
                echo DB_HOST=${{ secrets.DB_HOST }} >> .env
                echo DB_DATABASE=postgres >> .env

                echo GOOGLE_OAUTH_CLIENT_ID=1079616795937-oo3obhti3cv2npc4j6i06l5pq61v7925.apps.googleusercontent.com >> .env
                echo HTTP_SESSION_DOMAIN=abop.ai >> .env
                echo HTTP_SESSION_SECRET=${{ secrets.HTTP_SESSION_SECRET }} >> .env

            - name: Set up .env file for homepage
              if: matrix.image == 'homepage'
              run: |
                touch .env
            
            - name: Set up .env file for auth
              if: matrix.image == 'auth'
              run: |
                touch .env
                echo OPENAI_TEMPERATURE=0 > .env
                echo OPENAI_API_KEY=${{ secrets.DEMO_OPENAI_API_KEY }} >> .env
                echo DB_DRIVER=postgresql+psycopg >> .env
                echo DB_USERNAME=postgres >> .env
                echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
                echo DB_PORT=5432 >> .env
                echo DB_HOST=${{ secrets.DB_HOST }} >> .env
                echo DB_DATABASE=postgres >> .env

                echo HTTP_CORS_ORIGINS=*.abop.ai >> .env
                echo HTTP_SESSION_DOMAIN=abop.ai >> .env
                echo HTTP_SESSION_SECRET=${{ secrets.HTTP_SESSION_SECRET }} >> .env
                echo SAAS_AUTH_REDIRECT=https://app-staging.abop.ai >> .env

                echo GOOGLE_OAUTH_CLIENT_ID=1079616795937-oo3obhti3cv2npc4j6i06l5pq61v7925.apps.googleusercontent.com >> .env
                echo GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} >> .env
                echo GOOGLE_OAUTH_REDIRECT_URIS=https://abop.ai >> .env
                echo GOOGLE_OAUTH_REDIRECT=https://auth-staging.abop.ai/auth >> .env

            - uses: astral-sh/setup-uv@v3
              with: 
                version: "0.4.27"

            - name: Deploy to ECS
              run: |
                uv run python -m concrete deploy \
                    --image-uri 008971649127.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.image }}:latest \
                    --container-name ${{ matrix.image }}-staging \
                    --container-port 80 \
                    --container-env-file .env \
                    --security-groups sg-01af4e696bd2679c3 \
                    --subnets subnet-0644cadc735c6b557
                    --listener-arn arn:aws:elasticloadbalancing:us-east-1:008971649127:listener/app/ConcreteStagingLB/14b30997c81f806e/5f6189397e559d46 \
                    --health-check-path /ping
permissions:
  id-token: write 
  contents: read 