name: Deploy Docs to Staging
run-name: Deploy Docs to Staging }
on:
    push:
        branches:
            - main
            - michael/sdk_docs
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Configure AWS credentials for ECR
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecr-write-access
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  mask-password: "true"

            - uses: astral-sh/setup-uv@v3
              with: 
                version: "0.4.27"

            - run: uv sync --all-extras --dev

            - name: Build the docs image
              run: make build-docs

            - name: Push to ECR
              run: make aws-ecr-push-docs
    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: astral-sh/setup-uv@v3
              with: 
                version: "0.4.27"

            - uses: actions/setup-python@v5
              with:
                python-version: "3.11.9"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS Credentials for ECS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
                  aws-region: us-east-1

            - name: Deploy to ECS staging using AwsTool._deploy_service
              run: |
                  uv run python -m concrete deploy \
                    --image-uri 008971649127.dkr.ecr.us-east-1.amazonaws.com/docs:latest \
                    --container-name docs-staging \
                    --container-port 80 \
                    --container-env-file "" \
                    --service-name docs-staging \
                    --security-groups sg-01af4e696bd2679c3 \
                    --subnets subnet-0644cadc735c6b557 \
                    --listener-arn arn:aws:elasticloadbalancing:us-east-1:008971649127:listener/app/ConcreteStagingLB/14b30997c81f806e/5f6189397e559d46

permissions:
  id-token: write 
  contents: read