name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-Agents:
    runs-on: ubuntu-latest
    steps:
      env:
        OPENAI_API_KEY = ${{secrets.OPENAI_API_KEY}}
      run:
        echo 'hello world'
        

