name: Deploy SaaS to Staging
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Configure AWS credentials for ECR
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecr-write-access
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  mask-password: "true"

            - name: Build the images
              run: |
                  echo OPENAI_TEMPERATURE=0 > .env
                  echo OPENAI_API_KEY=$OPENAI_API_KEY >> .env 
                  echo DB_DRIVER=postgresql+psycopg >> .env
                  echo DB_USERNAME=postgres >> .env
                  echo DB_PASSWORD=$POSTGRES_STAGING_PASSWORD >> .env
                  echo DB_PORT=5432 >> .env
                  echo DB_HOST=staging-db.c3auqaqcunqy.us-east-1.rds.amazonaws.com >> .env
                  echo DB_DATABASE=postgres >> .env

                  echo HTTP_ALLOWED_HOSTS=$HTTP_ALLOWED_HOSTS >> .env
                  echo HTTP_CORS_ORIGINS=$HTTP_CORS_ORIGINS >> .env
                  echo HTTP_SESSION_DOMAIN=$HTTP_SESSION_DOMAIN >> .env
                  echo HTTP_SESSION_SECRET=$HTTP_SESSION_SECRET >> .env
                  echo SAAS_AUTH_REDIRECT=$SAAS_AUTH_REDIRECT >> .env

                  echo GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID >> .env
                  echo GOOGLE_OAUTH_CLIENT_SECRET=$GOOGLE_OAUTH_CLIENT_SECRET >> .env
                  echo GOOGLE_OAUTH_REDIRECT_URIS=$GOOGLE_OAUTH_REDIRECT_URIS >> .env
                  echo GOOGLE_OAUTH_REDIRECT=$GOOGLE_OAUTH_REDIRECT >> .env

                  make build-main
            - name: Push to ECR
              run: |
                  make aws-ecr-push-main
    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Setup Python for poetry
              uses: actions/setup-python@v5
              with:
                python-version: "3.11.9"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS Credentials for ECS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
                  aws-region: us-east-1

            - name: Deploy to ECS staging using AwsTool._deploy_service
              env: 
                POSTGRES_STAGING_PASSWORD: ${{secrets.POSTGRES_STAGING_PASSWORD}}
              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  poetry --version
                  poetry install
                  poetry run python -m concrete deploy \
                    --image-uri 008971649127.dkr.ecr.us-east-1.amazonaws.com/main:latest \
                    --container-name main-staging \
                    --container-port 80 \
                    --service-name main-staging \
                    --listener-rule-field host-header \
                    --listener-rule-value app-staging.abop.ai \
                    --container-envs "[[{'name': 'OPENAI_TEMPERATURE', 'value': '0'}, {'name': 'DB_DRIVER', 'value': 'postgresql+psycopg'}, {'name': 'DB_USERNAME', 'value': 'postgres'}, {'name': 'DB_PASSWORD', 'value': '$POSTGRES_STAGING_PASSWORD'}, {'name': 'DB_PORT', 'value': '5432'}, {'name': 'DB_HOST', 'value': 'database-1.c3auqaqcunqy.us-east-1.rds.amazonaws.com'}, {'name': 'DB_DATABASE', 'value': 'postgres'}]]"

# https://github.com/actions/deploy-pages/issues/329 -
# https://github.com/github/docs/issues/32320 - Explains why id-token write is needed
# The id-token: write permission provides a workflow the ability to interact with external services that use OpenID Connect (OIDC).
permissions:
  id-token: write 
  contents: read