name: Deploy SaaS to Staging
on:
    push:
        branches:
            - main
            - michael/deploy_to_prod
jobs:
    build:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Configure AWS credentials for ECR
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecr-write-access
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                  mask-password: "true"

            - name: Build the images
              run: |
                  touch .env
                  make build-main
            - name: Push to ECR
              run: |
                  make aws-ecr-push-main
    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Setup Python for poetry
              uses: actions/setup-python@v5
              with:
                python-version: "3.11.9"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure AWS Credentials for ECS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::008971649127:role/gha-ecs-full-access
                  aws-region: us-east-1

            - name: Deploy to ECS staging using AwsTool._deploy_service
              env: 
                POSTGRES_STAGING_PASSWORD: ${{secrets.POSTGRES_STAGING_PASSWORD}}
              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  poetry --version
                  poetry install
                  poetry run python -m concrete deploy \
                    --image-uri 008971649127.dkr.ecr.us-east-1.amazonaws.com/main:latest \
                    --container-name main-staging \
                    --container-port 80 \
                    --service-name main-prod \ 
                    --listener-rule-field host-header \
                    --listener-rule-value main.abop.ai \ 
                    --container-env "[{'name': 'OPENAI_TEMPERATURE', 'value': '0'}, \
                                      {'name': 'DB_DRIVER', 'value': 'postgresql+psycopg'}, \
                                      {'name': 'DB_USERNAME', 'value': 'postgres'}, \
                                      {'name': 'DB_PASSWORD', 'value': '${POSTGRES_STAGING_PASSWORD}'}, \
                                      {'name': 'DB_PORT', 'value': '5432'}, \
                                      {'name': 'DB_HOST', 'value': 'production-db.c3auqaqcunqy.us-east-1.rds.amazonaws.com'}, \
                                      {'name': 'DB_DATABASE', 'value': 'postgres'}]"

# https://github.com/actions/deploy-pages/issues/329 -
# https://github.com/github/docs/issues/32320 - Explains why id-token write is needed
# The id-token: write permission provides a workflow the ability to interact with external services that use OpenID Connect (OIDC).
permissions:
  id-token: write 
  contents: read