name: Unit Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    paths:
    - '**.py'
env:
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

jobs:
  Test-Agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Setup Poetry
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install
      
      - name: Run tests
        run: poetry run python -m pytest


