name: Unit Test
run-name: Unit Test ${{ github.actor }}
on: [push]

jobs:
  Test-Agents:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml" 
      
      - run: |
          touch .env
          echo HTTP_SESSION_DOMAIN=${{ secrets.HTTP_SESSION_DOMAIN }} > .env
          echo HTTP_SESSION_SECRET=${{ secrets.HTTP_SESSION_SECRET }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo POSTGRES_VECTOR_DB_DATABASE=${{ secrets.POSTGRES_VECTOR_DB_DATABASE}} >> .env
          echo POSTGRES_VECTOR_DB_DRIVER=${{ secrets.POSTGRES_VECTOR_DB_DRIVER }} >> .env
          echo POSTGRES_VECTOR_DB_HOST=${{ secrets.POSTGRES_VECTOR_DB_HOST }} >> .env
          echo POSTGRES_VECTOR_DB_PASSWORD=${{ secrets.POSTGRES_VECTOR_DB_PASSWORD }} >> .env
          echo POSTGRES_VECTOR_DB_PORT=${{ secrets.POSTGRES_VECTOR_DB_PORT }} >> .env
          echo POSTGRES_VECTOR_DB_USERNAME=${{ secrets.POSTGRES_VECTOR_DB_USERNAME }} >> .env
          echo POSTGRES_VECTOR_STORE_TABLE=${{ secrets.POSTGRES_VECTOR_STORE_TABLE }} >> .env
          echo SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }} >> .env

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run python -m pytest 

